### ISSUE TITLE
KeyError: 'employee-bonus'

### ISSUE THREAD

**Issue by phommata** [nikhil-ravi/LeetScrape#2]
Using the example code, during `get_similar_questions`, the `KeyError: 'employee-bonus'` is raised

```
poetry run python3 main.py
Scraping companies ... Done
Scraping questions list ... Done
Extracting question topics ... Done
Getting Categories ... Done
Scraping Topic Tags ... Done
Extracting question category ... Done
174it [03:40,  1.27s/it]
Traceback (most recent call last):
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'employee-bonus'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leetscraper/Documents/GitHub/LeetScrape/src/main.py", line 14, in <module>
    questions_body_list = get_all_questions_body(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Documents/GitHub/LeetScrape/src/leetscrape/utils.py", line 63, in get_all_questions_body
    questions_info_list.append(GetQuestionInfo(titleSlug).scrape())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Documents/GitHub/LeetScrape/src/leetscrape/GetQuestionInfo.py", line 111, in scrape
    SimilarQuestions=self.get_similar_questions(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Documents/GitHub/LeetScrape/src/leetscrape/GetQuestionInfo.py", line 135, in get_similar_questions
    similar_questions.append(self.questions_info.loc[qs["titleSlug"]].QID)
                             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/generic.py", line 4056, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/leetscraper/Library/Caches/pypoetry/virtualenvs/leetscrape-AMAFZmrp-py3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'employee-bonus'
```

**Comment by TahaTobaili** [comment]
I got the same error here, exactly at 174it as well. 
@nikhil-ravi thanks for a great library, can you please have a look at this? 

Thanks!

**Comment by nikhil-ravi** [comment]
https://github.com/nikhil-ravi/LeetScrape/blob/97d99d8629350a4e8f4f541a1f25868f466f8dd2/src/leetscrape/GetQuestionInfo.py#L52

It seems that Leetcode made some changes to their internal API, specifically affecting the listing of SQL questions. The previous API https://leetcode.com/api/problems/algorithms/ no longer includes certain SQL questions, like the `employee-bonus` problem.

By trial and error, I was able to get the database questions api endpoint: https://leetcode.com/api/problems/database/

I have made the changes to fix iteration 174 that scrapes the [175. Combine Two Tables](https://leetcode.com/problems/combine-two-tables/) question and other iterations that were affected. 

Testing against the entire database now.
Will push an update soon.


---
edit:

It looks like the API endpoint was split into these categories:
![image](https://github.com/nikhil-ravi/LeetScrape/assets/10914825/2514542a-27de-4e24-b004-57459adff95e)

The new endpoint https://leetcode.com/api/problems/all/ seems to contain all the questions.
